/**
 * Reference texts for each dictation.
 *
 * The texts keep British typographic apostrophes (’) where the source used them.
 * Normalising them is `tokenise`'s job, so both a curly and a straight apostrophe
 * typed by a student compare equal — see `lib/diff.ts`.
 */
export const DICTATIONS: Record<number, string> = {
  118: `Running short of space while painting, we had to stand our mattress vertically against the bedroom wall. The crush on the morning train can put me in an awful mood. The corkscrew slipped from my hand and fell straight into the bowl of sauce, which earned me a round of applause from my guests. My cat had a good long stretch before trying the sour cream I’d placed in front of her. If he goes on acting like this, the respect that his staff currently feel for him will quickly fade. Only a fool would believe that a tame lion isn’t still a dangerous animal. Ditch, cough, reward, swear, goat.`,

  119: `There’ll be little sorrow at the king’s departure. Am I going deaf or is our teacher quiet? It’s almost like he’s whispering sometimes! A war journalist needs to be both curious and courageous. Whatever you do, don’t spill that ink; it’d leave a terrible stain on the carpet. I’m keen to sell this fruit as quickly as possible. It’s already looking a bit overripe, and we’ve got tons of it left. The actual concert venue doesn’t open till eight, so, meanwhile, why don’t we enjoy the warmth of that bar? The film was ruined for her owing to the constant sound of sneezing from the row behind her. Swallow, patience, cushion, decay, coward.`,

  120: `Despite knowing it was out of bounds, the three children chose to disobey their uncle and open the cupboard. They then quickly removed all the toys from the cardboard box inside. Some men build up their muscles so much that simply walking can be awkward. Woven into the cloth was a variety of absurd designs, which suggested the artist had never attended art school. The area where those bees stung you is getting quite swollen now. The entire health and safety committee threatened to resign unless those in authority agreed to introduce a programme of urgent changes at the factory. Suspicion, precious, solemn, collar, adjust.`,

  121: `The garden lies on a steep slope and the soil’s thin, but let’s sow a few seeds anyway and hope for the best. The policemen were puzzled when the old woman who owned the cottage just carried on combing her hair and ignored them. I’m delighted my mechanic thinks the tyres don’t need changing. A shiver ran down Adam’s spine on realizing the burglar had stolen his girlfriend’s jewellery from the hidden drawer. Take my gloves, the circular saw, and this bundle of tools, and put them all with the other stuff in the garage. You’ll lose a lot of the flavour if you cook that dish on the hob instead of in the oven. Amateur, option, encounter, bracelet, knuckle.`,

  122: `The cyclist stopped to pump more air into his tyres, in the hope that this would ensure that he didn’t get a puncture on the narrow, bumpy countryside lanes. Leading the procession, looking far from graceful squeezed into his military uniform, was the monarch himself, accompanied by a dozen armed guards. Have you no conscience? This is a clear case of prejudice! You certainly weren’t exaggerating about the scenery; the bay looks simply magnificent from up here! Mike was aware that few journalists had ever been permitted a personal interview with the team’s coach, who had acquired a reputation for being grumpy and even nasty with members of the press. Accessory, suicide, bankrupt, relevant, author.`,

  123: `It was by no means a desperate time for her after the divorce; in fact, she coped very well indeed. Neither of us can stand using the vacuum cleaner, so what’s stopping us paying someone to do the household chores while we’re at work? Let’s hope the bridegroom gives a decent speech. Richard glanced up and was thrilled to spot the marvellous city lights ahead. It had been a long, tedious train journey, but soon he’d be home again, catching up with family and friends. This sweater I knitted is fabulous but slightly too large. Can I deliberately shrink it in the washing machine? Children often go through a stubborn phase when they rebel against their parents’ authority. Perceive, loathe, overdraft, leisure, pursue.`,

  124: `It’d been a dreadful plan. In an ambitious attempt to discourage other runners, Paula had shot ahead, but after a mere five miles, she was being overtaken. So exhausted that she felt she might even collapse, she now stood no chance of a medal. This is outrageous! The architect’s initial sketches for the hotel project show that he plans to support the ceiling in the lounge with stone columns. He claims it’ll give the area a luxurious appeal, but I think it’s an appalling idea, and would just look weird. My proudest moment as an inventor was watching the aircraft launch into the atmosphere full of technological equipment that I’d designed. Soon, it’d be sending back invaluable scientific information. Recruit, forthcoming, vehicle, plough, laundry.`,

  125: `John frowned at the barbecue, unable to comprehend. Although the heat seemed fierce, lifting up the shoulder of lamb and peering underneath had revealed the meat was somehow not cooking. The only way to beat a bully is to stand up for yourself. If possible, I’d appreciate a moment of your time. I’m conducting a survey on behalf of the local council to assess public opinion on the new retail development. In order to stop putting on weight, it’s crucial that you commit to this diet. Suspicious that the food company might not be complying with regulations, we took a closer look at the label on the packet. Adequate, budget, facial, exhibit, swap.`,

  126: `My recommendation would be to wind tape around the handle of the racket. Then you’ll be able to grasp it more firmly. Acting as casually as he could, Charles disguised his nerves at the wedding reception by contributing to conversations with what he hoped were humorous remarks. Don’t yawn in the queen’s presence; she’ll take offence because it implies you’re bored. Sally pulled the toddler onto her lap and gave her a hug. There’s no danger whatsoever of straining a muscle on this exercise machine providing you use the correct technique. In light of the research, it’s clear we need to implement measures to ensure this unique species of snake doesn’t get wiped out. Simultaneous, antique, feeble, route, worthwhile.`,

  127: `The rumour was that George had become rather chubby. My team's assignment had been to capture the heir to the throne and then withdraw to friendly territory. It would have been quite a feat, but we failed. The referee awarded a penalty kick for my foul, and they scored. I was furious with myself. Sales have been dismal recently, and revenue has plunged. We might have to make people redundant. The ship's anchor was stuck, so the cruise was held up while the crew worked out how to free it. We're moving to a spacious three-storey house in the suburbs. There's no guarantee that the next version of the programme won't contain errors. Persuasive, umpire, literature, outskirts, antique.`,

  128: `Her bike was parked outside the building but there was no trace of her inside. In the distance, I could just make out my train pulling out of the station. I sighed and turned back; perhaps someone would give me a lift. The catering company acknowledges that there's a hygiene issue in their kitchens. The twins were dizzy and thirsty from playing in the sun, but gulping down all that milk only made them sick. I was startled when he showed up because he looked nothing like his online profile! Theoretically, I could finance my university course myself but, even so, a scholarship covering my tuition fees would help. Harry confessed, and led the officers down to the cellar, insistent that printing the forgeries had not been his idea. Tackle, clumsy, occurrence, soggy, munch.`,

  129: `With so many passengers squashed into the carriage in the intense heat, it came as no surprise when someone passed out. Frank was a shabby sight, soaked to the skin and muttering angrily to himself as he squelched across the kitchen floor in his boots. Don't allow any rowdy groups of men into the club; they're bound to cause chaos. It's tricky to gauge how much we can expect to gain by investing in the scheme. Obviously, we're hoping prices soar. Don't just nibble the crust; take a big bite. I feel she came across as knowledgeable and very enthusiastic in the interview, and I took to her immediately. After the rehearsal, the director mingled with the cast in the theatre bar. Grudge, smoulder, orphan, insight, throb.`,

  130: `This design flaw is supposedly our fault, but they can't sue us. My dog growled at me when I removed the bone that it was chewing on. Tim blushed at the mention of the mysterious blonde girl I'd seen him with. I watched in awe as the other team thrashed us, scoring four goals in fifteen minutes. I'll endeavour to stay awake but may well doze off. I acknowledge I have no flair for art. A draught is usually annoying, whereas a breeze can be pleasant. The kids watched in sheer delight as the ducks waddled towards the water's edge. The veins on the back of my hands are especially visible in hot weather. Drought, ledge, hurtle, biased, wreath.`,
};

/** Dictation numbers, ascending — drives the select in the UI. */
export const DICTATION_NUMBERS: number[] = Object.keys(DICTATIONS)
  .map(Number)
  .sort((a, b) => a - b);
